# Guadagni (Per Ordine)

range="F2:F14"
[[cases]]
name = "Valori"
weight = 2
[cases.tests]
match_values = [60.00,175.00,72.50,114.00,52.00,25.00,37.50,20.00,20.00,15.00,12.00,150.00,15.00]
[[cases]]
weight = 1
name = "Formula Efficiente"
[cases.tests]
is_formula = true
no_formula_drift = true
