# Totale Prodotto (Per tipo di Pane)

range="E18:E21"

[prerequisite]
name = "Valori"
weight = 2

[prerequisite.cases]
match_solution_values = true

[[cases]]
weight = 1
name = "Formula Efficiente"

[cases.tests]
is_formula = true
no_formula_drift = true