# Totale Venduto (Per tipo di Pane)

range="F18:F21"
[[cases]]
name = "Valori"
weight = 2
[cases.tests]
match_values = [360,440,560,100]
[[cases]]
weight = 1
name = "Formula Efficiente"
[cases.tests]
is_formula = true
no_formula_drift = true