# Usage:
#
# range = <str>       : [Required] A valid Calc range, e.g. "A1:C3"
# show_range = <bool> : [Optional] If False, range is hidden

# [prerequisite] : [Optional] A single prerequisite testcase to be ran before the others
# < See `TestCase` >
#
# [[cases]] : [Optional] A list of `TestCase`s structured the same as a prerequisite
# < See `TestCase` >
#
# def `TestCase`:
#   Either : { 
#     name = <str>    : [Required]
#     weight = <int>  : [Optional] [Default = 1] The relative weight of this case when grading this TestSet
#   
#     [`<ParentName>`.tests] 
#     match_values = [<str|int>, ...]  : [Optional] cells must match these exact values
#     match_solution_values = <bool>   : [Optional] True if cells must match provided solution values
#     is_formula = <bool>              : [Optional] True if cells must contain formulas
#     is_bold = <bool>                 : [Optional] True if cells must be bold
#     no_formula_drift = <bool>        : [Optional] True if all formulas must be identical across the range
#     has_bgcolor = <bool>             : [Optional] True if cells must have any background color
#     match_bgcolor = "<hex color>"    : [Optional] exact background color required, e.g., "#FFFF00"
#   }
#   Or : {
#     from_template = <key>   : [Required] Loads a template 
#     name = <str>            : [Optional] Override default template name
#   }
#
# Example:

#TODO